{% set name = "rollbar" %}
{% set version = "0.14.1" %}
{% set sha256 = "a629babe937869c6ca0386edca96b3e434e6f40cbc169aca0578ca72fb694734" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - rollbar = rollbar.cli:main

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - requests >=0.12.1
    - six >=1.9.0

test:
  requires:
    - unittest2
    - mock
    - webob
    - blinker
    - pytest
  imports:
    - rollbar
    - rollbar.test
  commands:
    - py.test --pyargs rollbar
    - rollbar --help

about:
  home: https://github.com/rollbar/pyrollbar
  license: MIT
  license_family: MIT
  summary: 'Rollbar notifier for Python'

  description: |
    Python notifier for reporting exceptions, errors, and log messages to Rollbar.
  doc_url: https://rollbar.com/docs/notifier/pyrollbar/

extra:
  recipe-maintainers:
    - TheOriginalAlex
