travis:
  secure:
    BINSTAR_TOKEN: GR9/3D36kgGj79rZEtUSWJQZAGxpLHInNKsWMNOH1gID8k7msSxiJWiwGD+Fp4gHTYu5kDHToATfpbm1WxpmCUO6NzXcFg3a8ho4oxx2XWIVW0pe+RpVNRAA6SoYxC8x+55D9Br4W+iMgd2mW30b/dr0FKNoxPEVAv8BF43aHF1+BvSAJzQ6RRUqEkDLBHA3503HG0d57EN9fs7rN+R8PWh9oxmjOp0Twch4619Y33e2ab8JL6g4iBNTnkcAEASsbHGvtp0Bux2JvDLaZk7gpPH7ugSlv/LLRi/Oy4V81hd4Z4qMC2FE6ctwb8CZVJKQ7nODayJa3jhhaFYZNiuTaFdHxHLBKg3+46ULmkWDdDJwIfb0faTZ/Xgl4KoG2JEqxebA+q+teMKlzS2ksHqs1SzVAXFT2Lg09Ao8VpvgUXoDHfS+rCIxRzEhR8OiYekCnQwikYcJdOGvNxSPg+9BJ/VMwGmFX/FZchZEDJ0WoGcCbflkVlDgIPectGjBC1AAdnxVgg3ksf31K1eDVtxP75pPmnulNkgRSoFOhCxpvKsEtEjT0LCN6eYYWOD/xVvO+L61V86kR1KHZLUJIWX5NO/7fXt8K8z131zRuH9dHhljkc2GddLGeE1Wv8h5gu+/g0Lp0bK/OavFkg1gBVuoyfdcCd5sUZ+BYDg2vhUKvKY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
