travis:
  secure:
    BINSTAR_TOKEN: dwOclSoDgkt51tL6UPq1lHSX6iPP5MBB6UU72G2k5a0tYbKwiTi9wSVwLe3eOqvD10j2aDgS/N350x2WEUGYbHThbgXy0QKqW/k7pfQbdecHMwRrjqlYbQQomzygZN3GVm2hVyjUSYs/V2ZtBLNkNzQ1kOVgOb6Osa3FjWaWOXb9PDmavhczP5VenCbF9kzb6QPQGnadL0tkY8xvRbMWkvSGGkbx4N6uc+ftNOfXATgtWoQpkcZQBhwfdcdDHDzwa1N6Fv6RYTyVsiv55KDBIknTLAa8BatFtbBI6ji10+so5HThP4XjXcI7U6Er4XFusHMohCmjl0MCvWaE0EDi9Ew6vHxBHF856LuG8pfrGnAKh4uOT02qTLtACaUTTlfBl+qXA5o6owg+6vlqFQi4TZBSv5IIk+q5EyaUsqCcmRPuUxWn2LUo8JmNa565hZQHjTLnBOC9D60h7hLwaQsoykcWXYawqP/w2H2WUZNrb6nD4xl3w6ArrUUBO8MR50bBZlMQdauabhopw/jkb42brm2shUnsdfVP/iPNyGLh3aTCq/KCi7jaHkyQFUb+9Ti/dFh9tPNqoofyIyDgVf3G2ycVs2XE2PEsXnxUse4IOlSHC/GnY0GjeWlSmkc/YRAT27caxvQezEc7dzU0EJjNatLqb4V3lDWu/eJvYV48pVM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
